title: Korrekturformular
fields:
  -
    import: title
  -
    handle: eligibility_year
    field:
      type: text
      display: 'Jahr Jurierung'
      instructions: 'Wird für die korrekte Berechnung der Altersgrenze im Formular benötigt.'
      localizable: false
      instructions_position: below
  -
    handle: introduction
    field: editor.editor
    config:
      display: Einleitungstext
      localizable: true
