title: Settings
fields:
  -
    handle: template
    field:
      type: template
      display: Template
      localizable: false
  -
    handle: layout
    field:
      type: template
      display: Layout
      localizable: false
  -
    handle: has_footer
    field:
      default: true
      type: toggle
      display: 'Footer anzeigen?'
      localizable: false
